// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/calendar/calendar.proto

package calendar_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetEventsDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsDayRequest) Reset() {
	*x = GetEventsDayRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsDayRequest) ProtoMessage() {}

func (x *GetEventsDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsDayRequest.ProtoReflect.Descriptor instead.
func (*GetEventsDayRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventsDayRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventsDayRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetEventsDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsDayResponse) Reset() {
	*x = GetEventsDayResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsDayResponse) ProtoMessage() {}

func (x *GetEventsDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsDayResponse.ProtoReflect.Descriptor instead.
func (*GetEventsDayResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventsDayResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartOfWeek   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_of_week,json=startOfWeek,proto3" json:"start_of_week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsWeekRequest) Reset() {
	*x = GetEventsWeekRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsWeekRequest) ProtoMessage() {}

func (x *GetEventsWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsWeekRequest.ProtoReflect.Descriptor instead.
func (*GetEventsWeekRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventsWeekRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventsWeekRequest) GetStartOfWeek() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfWeek
	}
	return nil
}

type GetEventsWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsWeekResponse) Reset() {
	*x = GetEventsWeekResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsWeekResponse) ProtoMessage() {}

func (x *GetEventsWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsWeekResponse.ProtoReflect.Descriptor instead.
func (*GetEventsWeekResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsWeekResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartOfMonth  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_of_month,json=startOfMonth,proto3" json:"start_of_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsMonthRequest) Reset() {
	*x = GetEventsMonthRequest{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsMonthRequest) ProtoMessage() {}

func (x *GetEventsMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsMonthRequest.ProtoReflect.Descriptor instead.
func (*GetEventsMonthRequest) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsMonthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventsMonthRequest) GetStartOfMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfMonth
	}
	return nil
}

type GetEventsMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsMonthResponse) Reset() {
	*x = GetEventsMonthResponse{}
	mi := &file_proto_calendar_calendar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsMonthResponse) ProtoMessage() {}

func (x *GetEventsMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calendar_calendar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsMonthResponse.ProtoReflect.Descriptor instead.
func (*GetEventsMonthResponse) Descriptor() ([]byte, []int) {
	return file_proto_calendar_calendar_proto_rawDescGZIP(), []int{10}
}

func (x *GetEventsMonthResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_calendar_calendar_proto protoreflect.FileDescriptor

const file_proto_calendar_calendar_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/calendar/calendar.proto\x12\bcalendar\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"\xc9\x01\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"0\n" +
	"\x13CreateEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xe4\x01\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"H\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"^\n" +
	"\x13GetEventsDayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"?\n" +
	"\x14GetEventsDayResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"o\n" +
	"\x14GetEventsWeekRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\rstart_of_week\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vstartOfWeek\"@\n" +
	"\x15GetEventsWeekResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"r\n" +
	"\x15GetEventsMonthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12@\n" +
	"\x0estart_of_month\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fstartOfMonth\"A\n" +
	"\x16GetEventsMonthResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events2\xdd\x03\n" +
	"\x0fCalendarService\x12J\n" +
	"\vCreateEvent\x12\x1c.calendar.CreateEventRequest\x1a\x1d.calendar.CreateEventResponse\x12C\n" +
	"\vUpdateEvent\x12\x1c.calendar.UpdateEventRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\vDeleteEvent\x12\x1c.calendar.DeleteEventRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\fGetEventsDay\x12\x1d.calendar.GetEventsDayRequest\x1a\x1e.calendar.GetEventsDayResponse\x12P\n" +
	"\rGetEventsWeek\x12\x1e.calendar.GetEventsWeekRequest\x1a\x1f.calendar.GetEventsWeekResponse\x12S\n" +
	"\x0eGetEventsMonth\x12\x1f.calendar.GetEventsMonthRequest\x1a .calendar.GetEventsMonthResponseB8Z6github.com/ilindan-dev/event-calendar/calendar-serviceb\x06proto3"

var (
	file_proto_calendar_calendar_proto_rawDescOnce sync.Once
	file_proto_calendar_calendar_proto_rawDescData []byte
)

func file_proto_calendar_calendar_proto_rawDescGZIP() []byte {
	file_proto_calendar_calendar_proto_rawDescOnce.Do(func() {
		file_proto_calendar_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)))
	})
	return file_proto_calendar_calendar_proto_rawDescData
}

var file_proto_calendar_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_calendar_calendar_proto_goTypes = []any{
	(*Event)(nil),                  // 0: calendar.Event
	(*CreateEventRequest)(nil),     // 1: calendar.CreateEventRequest
	(*CreateEventResponse)(nil),    // 2: calendar.CreateEventResponse
	(*UpdateEventRequest)(nil),     // 3: calendar.UpdateEventRequest
	(*DeleteEventRequest)(nil),     // 4: calendar.DeleteEventRequest
	(*GetEventsDayRequest)(nil),    // 5: calendar.GetEventsDayRequest
	(*GetEventsDayResponse)(nil),   // 6: calendar.GetEventsDayResponse
	(*GetEventsWeekRequest)(nil),   // 7: calendar.GetEventsWeekRequest
	(*GetEventsWeekResponse)(nil),  // 8: calendar.GetEventsWeekResponse
	(*GetEventsMonthRequest)(nil),  // 9: calendar.GetEventsMonthRequest
	(*GetEventsMonthResponse)(nil), // 10: calendar.GetEventsMonthResponse
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 12: google.protobuf.Empty
}
var file_proto_calendar_calendar_proto_depIdxs = []int32{
	11, // 0: calendar.Event.start_time:type_name -> google.protobuf.Timestamp
	11, // 1: calendar.Event.end_time:type_name -> google.protobuf.Timestamp
	11, // 2: calendar.CreateEventRequest.start_time:type_name -> google.protobuf.Timestamp
	11, // 3: calendar.CreateEventRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 4: calendar.UpdateEventRequest.start_time:type_name -> google.protobuf.Timestamp
	11, // 5: calendar.UpdateEventRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 6: calendar.GetEventsDayRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 7: calendar.GetEventsDayResponse.events:type_name -> calendar.Event
	11, // 8: calendar.GetEventsWeekRequest.start_of_week:type_name -> google.protobuf.Timestamp
	0,  // 9: calendar.GetEventsWeekResponse.events:type_name -> calendar.Event
	11, // 10: calendar.GetEventsMonthRequest.start_of_month:type_name -> google.protobuf.Timestamp
	0,  // 11: calendar.GetEventsMonthResponse.events:type_name -> calendar.Event
	1,  // 12: calendar.CalendarService.CreateEvent:input_type -> calendar.CreateEventRequest
	3,  // 13: calendar.CalendarService.UpdateEvent:input_type -> calendar.UpdateEventRequest
	4,  // 14: calendar.CalendarService.DeleteEvent:input_type -> calendar.DeleteEventRequest
	5,  // 15: calendar.CalendarService.GetEventsDay:input_type -> calendar.GetEventsDayRequest
	7,  // 16: calendar.CalendarService.GetEventsWeek:input_type -> calendar.GetEventsWeekRequest
	9,  // 17: calendar.CalendarService.GetEventsMonth:input_type -> calendar.GetEventsMonthRequest
	2,  // 18: calendar.CalendarService.CreateEvent:output_type -> calendar.CreateEventResponse
	12, // 19: calendar.CalendarService.UpdateEvent:output_type -> google.protobuf.Empty
	12, // 20: calendar.CalendarService.DeleteEvent:output_type -> google.protobuf.Empty
	6,  // 21: calendar.CalendarService.GetEventsDay:output_type -> calendar.GetEventsDayResponse
	8,  // 22: calendar.CalendarService.GetEventsWeek:output_type -> calendar.GetEventsWeekResponse
	10, // 23: calendar.CalendarService.GetEventsMonth:output_type -> calendar.GetEventsMonthResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_calendar_calendar_proto_init() }
func file_proto_calendar_calendar_proto_init() {
	if File_proto_calendar_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calendar_calendar_proto_rawDesc), len(file_proto_calendar_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calendar_calendar_proto_goTypes,
		DependencyIndexes: file_proto_calendar_calendar_proto_depIdxs,
		MessageInfos:      file_proto_calendar_calendar_proto_msgTypes,
	}.Build()
	File_proto_calendar_calendar_proto = out.File
	file_proto_calendar_calendar_proto_goTypes = nil
	file_proto_calendar_calendar_proto_depIdxs = nil
}
